### PR TITLE
Implement Android 10's edge-to-edge drawing recommendations

### PR DESCRIPTION
**Pull request by Skrilltrax**
Signed-off-by: Aditya Wasan <adityawasan55@gmail.com>

### CODE REVIEW

**Comment by Skrilltrax** [comment]
Fixes #183

**Comment by msfjarvis** [comment]
This looks _very_ off

**Comment by Skrilltrax** [comment]
Oh let me check again, are the other screens fine ?

**Comment by msfjarvis** [comment]
> Oh let me check again, are the other screens fine ?

Tunnel editor is fine, detail and list are broken.

**Comment by Skrilltrax** [comment]
Can you send me a SS of detail screen too, things seem to work fine on My poco f1 running PE 10.

**Pull request merged**
