### PR TITLE
New Crowdin translations (Chinese Simplified)

### PR DESCRIPTION
**Pull request by msfjarvis**
Enjoy!

### CODE REVIEW

**Comment by LilligantMatsuri** [comment]
Hello, I've finished the first edition of Simplified Chinese translation and (roughly) proofread it. I believe there can be some mistakes. After the translation is put into use, I'll review it in the app and make a revision. Feel free to let me know if there is anything I can help. ☺️

**Comment by LilligantMatsuri** [comment]
I don't have a Telegram account, so please send it here. Thank you.

**Comment by msfjarvis** [comment]
There you go https://dl.msfjarvis.dev/viscerion/viscerion_5.2.8-15-g9f8e13a7d8ae.apk

**Comment by LilligantMatsuri** [comment]
Got it, thanks. I'm going to check my translation then.

**Comment by msfjarvis** [comment]
All good with the translations?

**Comment by LilligantMatsuri** [comment]
I corrected some of them. You can merge the changes now. I'll keep on improving it.

**Comment by msfjarvis** [comment]
> I corrected some of them. You can merge the changes now. I'll keep on improving it.

Alright. I'm going to need to push a new release very soon so #225 will be merged and deployed to production.

**Pull request merged**
