### PR TITLE
Resolve hostnames to IP addresses when saving

### PR DESCRIPTION
**Pull request by msfjarvis**
DNS servers and endpoints often have hostnames attached to them which wg-quick and
VPNService cannot directly use. Resolve them to IP addresses using dnsjava before saving.

### CODE REVIEW

**Comment by msfjarvis** [comment]
@dcplaya I remember you had the issue as well, can you test [this](https://download.msfjarvis.website/viscerion/viscerion_5.1.1-168-gfac7ac12e9cc-release.apk) build and confirm it works for you?

**Comment by dcplaya** [comment]
I tried installing that beta but it fails to install.

**Comment by msfjarvis** [comment]
> I tried installing that beta but it fails to install.

It installs fine on both my phones, can you try to install it through ADB and show me what error it returns?

**Comment by msfjarvis** [comment]
Here's a [debug APK](https://download.msfjarvis.website/viscerion/viscerion_5.1.1-168-g7595ebc407be-debug.apk) to try your luck with, it has a different package name so you'll need to re-add your tunnels to it.

**Comment by dcplaya** [comment]
> Here's a [debug APK](https://download.msfjarvis.website/viscerion/viscerion_5.1.1-168-g7595ebc407be-debug.apk) to try your luck with, it has a different package name so you'll need to re-add your tunnels to it.

This beta version installed but
- Camera doesn't open when trying to import via QR code
- Endpoint still does not accept a FQDN:port (error is `Not a numeric address: vpn.FQDN.com`)

Ive attached the full log from the app as well. 
[viscerion-log.txt](https://github.com/msfjarvis/viscerion/files/3668820/viscerion-log.txt)

Also, in case you need to know
Phone : Pixel 3
Android Version: 10

**Comment by msfjarvis** [comment]
> This beta version installed but
> 
> * Camera doesn't open when trying to import via QR code
> * Endpoint still does not accept a FQDN:port (error is `Not a numeric address: vpn.FQDN.com`)
> 
> Ive attached the full log from the app as well.
> [viscerion-log.txt](https://github.com/msfjarvis/viscerion/files/3668820/viscerion-log.txt)
> 
> Also, in case you need to know
> Phone : Pixel 3
> Android Version: 10

I'll have to look at the camera thing later. For now it looks like `InetAddress` does not support custom ports and I'll have to switch to `InetSocketAddress`. Does WireGuard on Linux accept ports in the Endpoint?

**Comment by dcplaya** [comment]
> Does WireGuard on Linux accept ports in the Endpoint?

I believe it does but I am not 100% sure. I use the Edgerouter builds and I am able to set the endpoint

```
/usr/bin/wg set wg2 peer hiddenPeerPublicKey endpoint er1.device.FQDN.com:51820
```

I would assume the full blown linux version would allow that as well.

**Comment by msfjarvis** [comment]
> > Does WireGuard on Linux accept ports in the Endpoint?
> 
> I believe it does but I am not 100% sure. I use the Edgerouter builds and I am able to set the endpoint
> 
> ```
> /usr/bin/wg set wg2 peer hiddenPeerPublicKey endpoint er1.device.FQDN.com:51820
> ```
> 
> I would assume the full blown linux version would allow that as well.

It does accept ports in Endpoint and even enforces it. I think it's a problem with the Android 10 [InetAddresses](https://developer.android.com/reference/android/net/InetAddresses) class but I'll need to triage it with zx2c4 to confirm.

**Comment by msfjarvis** [comment]
Applying [this](https://github.com/msfjarvis/wireguard-android/commit/8ab462754fa254a582f9e2d7c54aa1cf3c5cd530) to the upstream client brings Endpoint parsing behaviour on Android 10 on par with Viscerion so doesn't look like a lot we can do here. I'm waiting for Jason to respond and we'll see what comes of it. Appreciate your patience!

**Comment by msfjarvis** [comment]
@dcplaya I think this is resolved, can you test [this build](https://download.msfjarvis.website/viscerion/viscerion_5.1.1-169-gf9b774648d28-debug.apk) and confirm?

**Comment by msfjarvis** [comment]
I don't think this PR will be needed anymore.

**Comment by msfjarvis** [comment]
> Yep! It accepted a FQDN and was able to connect with no issues!
> 
> (Still have the camera issue but you already know about that)

Awesome, thanks for letting me know.

**Pull request closed without merging**
